"$schema" = 'https://starship.rs/config-schema.json'

format = """
[░▒▓]({{colors.secondary_container.default.hex}})\
$os\
[](bg:{{colors.primary.default.hex}} fg:{{colors.secondary_container.default.hex}})\
$directory\
[](fg:{{colors.primary.default.hex}} bg:{{colors.surface_container_high.default.hex}})\
$git_branch\
$git_status\
[](fg:{{colors.surface_container_high.default.hex}} bg:{{colors.surface_container.default.hex}})\
$nodejs\
$rust\
$golang\
$php\
[ ](fg:{{colors.surface_container.default.hex}})\
$character"""

[os]
disabled = false
style = "bg:{{colors.secondary_container.default.hex}} fg:{{colors.primary.default.hex}}"
format = "[ $symbol]($style)"

[character]
disabled = false
# Transparent background (default) with Primary colored foreground
success_symbol = "[󰁕]({{colors.primary.default.hex}})"
error_symbol = "[󰁕]({{colors.error.default.hex}})"

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = "󰣇 "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = "󰈄 "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰈄 "
Gentoo = " "
HardenedBSD = "󰈄 "
Illumos = "󰈄 "
Linux = " "
Mabox = "󰈄 "
Macos = " "
Manjaro = " "
Mariner = "󰈄 "
MidnightBSD = "󰈄 "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈄 "
openSUSE = " "
OracleLinux = "󰈄 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Solus = " "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[directory]
style = "fg:{{colors.on_primary.default.hex}} bg:{{colors.primary.default.hex}}"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:{{colors.surface_container_high.default.hex}}"
format = '[[ $symbol $branch ](fg:{{colors.primary.default.hex}} bg:{{colors.surface_container_high.default.hex}})]($style)'

[git_status]
style = "bg:{{colors.surface_container_high.default.hex}}"
format = '[[($all_status$ahead_behind )](fg:{{colors.primary.default.hex}} bg:{{colors.surface_container_high.default.hex}})]($style)'

[nodejs]
symbol = ""
style = "bg:{{colors.surface_container.default.hex}}"
format = '[[ $symbol ($version) ](fg:{{colors.primary.default.hex}} bg:{{colors.surface_container.default.hex}})]($style)'

[rust]
symbol = ""
style = "bg:{{colors.surface_container.default.hex}}"
format = '[[ $symbol ($version) ](fg:{{colors.primary.default.hex}} bg:{{colors.surface_container.default.hex}})]($style)'

[golang]
symbol = ""
style = "bg:{{colors.surface_container.default.hex}}"
format = '[[ $symbol ($version) ](fg:{{colors.primary.default.hex}} bg:{{colors.surface_container.default.hex}})]($style)'

[php]
symbol = ""
style = "bg:{{colors.surface_container.default.hex}}"
format = '[[ $symbol ($version) ](fg:{{colors.primary.default.hex}} bg:{{colors.surface_container.default.hex}})]($style)'