"$schema" = 'https://starship.rs/config-schema.json'

format = """
[░▒▓](#324b4e)\
$os\
[](bg:#81d4dd fg:#324b4e)\
$directory\
[](fg:#81d4dd bg:#252b2c)\
$git_branch\
$git_status\
[](fg:#252b2c bg:#1a2121)\
$nodejs\
$rust\
$golang\
$php\
[ ](fg:#1a2121)\
$character"""

[os]
disabled = false
style = "bg:#324b4e fg:#81d4dd"
format = "[ $symbol]($style)"

[character]
disabled = false
# Transparent background (default) with Primary colored foreground
success_symbol = "[󰁕](#81d4dd)"
error_symbol = "[󰁕](#ffb4ab)"

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = "󰣇 "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = "󰈄 "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰈄 "
Gentoo = " "
HardenedBSD = "󰈄 "
Illumos = "󰈄 "
Linux = " "
Mabox = "󰈄 "
Macos = " "
Manjaro = " "
Mariner = "󰈄 "
MidnightBSD = "󰈄 "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈄 "
openSUSE = " "
OracleLinux = "󰈄 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Solus = " "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[directory]
style = "fg:#00363b bg:#81d4dd"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#252b2c"
format = '[[ $symbol $branch ](fg:#81d4dd bg:#252b2c)]($style)'

[git_status]
style = "bg:#252b2c"
format = '[[($all_status$ahead_behind )](fg:#81d4dd bg:#252b2c)]($style)'

[nodejs]
symbol = ""
style = "bg:#1a2121"
format = '[[ $symbol ($version) ](fg:#81d4dd bg:#1a2121)]($style)'

[rust]
symbol = ""
style = "bg:#1a2121"
format = '[[ $symbol ($version) ](fg:#81d4dd bg:#1a2121)]($style)'

[golang]
symbol = ""
style = "bg:#1a2121"
format = '[[ $symbol ($version) ](fg:#81d4dd bg:#1a2121)]($style)'

[php]
symbol = ""
style = "bg:#1a2121"
format = '[[ $symbol ($version) ](fg:#81d4dd bg:#1a2121)]($style)'